k9s:
  cluster: config.master
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
    - all
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
