[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Buttonless"
opacity = 0.92
blur = true

[window.padding]
x = 7
y = 10

[general]
import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]

