# themes from https://github.com/alacritty/alacritty-theme

import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]


[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Buttonless"
opacity = 0.92
blur = true

[window.padding]
x = 7
y = 10
