k9s:
  cluster: dh-demo-dmi
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
