k9s:
  cluster: orca-dev-dmi
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
