# Prompt format
format = """
[╭─](#background_color)$username$hostname $directory $git_branch $python
[╰─](fg:#background_color)$character
"""

palette = 'bira'
command_timeout = 1000

# Username module
[username]
show_always = true
style_user = "bold green"
style_root = "bg:#background_color fg:#error_color"
format = '[$user]($style)'

# Hostname module
[hostname]
ssh_only = false
style = "bold green"
format = '[@$hostname]($style)'

# Directory module
[directory]
style = "bold blue"
format = "[$path]($style)"

# Git branch module
[git_branch]
symbol = ""
style = "bold yellow"
format = '[$symbol‹$branch›]($style)'

# Character module (prompt symbol)
[character]
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold red)'

# Color variables (customize these)
[palettes.bira]
background_color = "#1e1e2e"
text_color = "#cdd6f4"
directory_color = "#89b4fa"
git_color = "#a6e3a1"
git_status_color = "#f38ba8"
error_color = "#f38ba8"
user_color="#000000"
